### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by 49ronind** [ilteoood/local_m3u8#309]
How to use this I'm kinda new can you help?

**Comment by ilteoood** [comment]
This project has a docker image ready to run.
To use it, you have to configure 2 environment variables:
- PATH_TO_SCAN: the local path used to search for video files
- BASE_URL: the url to prepend for each entry


This app expose 2 endpoints:
- /playlist, that return the last generated m3u8 playlist
- /playlist/generate, that generate and return a new m3u8 file
